### ISSUE TITLE
Set content of commits

### ISSUE THREAD

**Issue by benthayer** [benthayer/git-gud#245]
Related to #224 
Required by #238 
Required by #235 

Various levels require files with specific contents to be present in the commits. See #238 and #235 This functionality should be added or verified to exist/work smoothly if most of the needed methods are already in place.

**Comment by benthayer** [comment]
Here is an example of how we might use YAML to specify the contents of the commits.
```
1:
 name: Initial commit
 files:
    intro.txt:
     - Once upon a time, there was a princess
2:
 name: Added a middle
 files:
    intro.txt:
     - Once upon a time, there was a princess
    middle.txt:
     - She lived a very fulfilling life
3:
 name: Added an ending
 files:
    intro.txt:
     - Once upon a time, there was a princess
    middle.txt:
     - She lived
    ending.txt:
     - And then she died
M1:
 name: Merge branch ending into master
 files:
    intro.txt:
     - Once upon a time, there was a princess
    middle.txt:
     - She lived a very fulfilling life
    ending.txt:
     - And then she died
```
